---
  - hosts: all
    vars:
      node:
        version: v0.12.7
    sudo: yes

    tasks:
    - name: Ensure NTP is installed.
      yum: name=ntp state=present


    - name: Ensure NTP is running.
      service: name=ntpd state=started enabled=yes

    - name: Install basic for compilling
      yum: name={{ item }} state=present
      with_items:
        - gcc
        - gcc-c++
        - make
        - openssl-devel


    - name: Check if NodeJS is already downloaded
      stat: path=/tmp/node-{{ node.version }}.tar.gz
      register: nodefile

    - name: Get NodeJS
      get_url:
        url: "https://nodejs.org/dist/{{ node.version }}/node-{{ node.version }}.tar.gz"
        dest: "/tmp/"
        mode: 0755
      when: nodefile.stat.exists == False
      sudo: no

    - name: Check if NodeJS is extracted
      stat: path=/tmp/node-{{ node.version }}
      register: nodefolder

    - name: Extract NodeJS
      unarchive:
          src: "/tmp/node-{{ node.version}}.tar.gz"
          dest: "/tmp"
          copy: no
      when: nodefolder.stat.exists == False
      sudo: no

    - name: Verify if NodeJS is installed
      command: /usr/local/bin/node --version
      register: nodeversion

    - name: Install NodeJS
      shell: "{{ item }}"
      args:
        chdir: "/tmp/node-{{ node.version }}"
      with_items:
        - ./configure
        - make
        - make install
      when: nodeversion.stdout != node.version

    - name: Install Global NPM packages
      npm: name={{ item.name }} version={{ item.version }} state=present global=yes executable=/usr/local/bin/npm
      with_items:
        - { name: npm,    version: 3.3.10 }
        - { name: bower,  version: 1.6.5  }
      sudo: no
